version: "3.7"

services:
    app:
        build: ./
        restart: always
        environment:
            NODE_ENV: production
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: typedash.ssprojects.ca
            LETSENCRYPT_HOST: typedash.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network
            - typedash-network
    db:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_DB: typedash
            POSTGRES_USER: typedash
            POSTGRES_PASSWORD: pw
        networks:
            - typedash-network
        volumes:
            - ~/db_typedash:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    service-network:
        external: true
    typedash-network:
        driver: bridge
