const STATE = {
    WAITING: "WAITING",
    COUNTDOWN: "COUNTDOWN",
    PLAYING: "PLAYING",
};

const TEST_TYPE = {
    VALID: "VALID",
    AVAILABLE: "AVAILABLE",
    EXISTS: "EXISTS",
};

const FIELD_TYPE = {
    USERNAME: "USERNAME",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
};

export { STATE, TEST_TYPE, FIELD_TYPE };
