const ACCOUNT_TYPE = {
    ADMIN: 1,
    NORMAL: 2,
    GUEST: 3,
};

const STATE = {
    PREGAME: "PREGAME",
    COUNTDOWN: "COUNTDOWN",
    PLAYING: "PLAYING",
    POSTGAME: "POSTGAME",
};

const ROOM_ACTION = {
    NEXT_ROUND: "NEXT_ROUND",
    START_COUNTDOWN: "START_COUNTDOWN",
    CANCEL_COUNTDOWN: "CANCEL_COUNTDOWN",
};

const TEST_TYPE = {
    VALID: "VALID",
    AVAILABLE: "AVAILABLE",
    EXISTS: "EXISTS",
};

const FIELD_TYPE = {
    USERNAME: "USERNAME",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
};

export { ACCOUNT_TYPE, STATE, ROOM_ACTION, TEST_TYPE, FIELD_TYPE };
