const ACCOUNT_TYPE = {
    ADMIN: 1,
    NORMAL: 2,
    GUEST: 3,
};

const STATE = {
    PREGAME: "PREGAME",
    COUNTDOWN: "COUNTDOWN",
    PLAYING: "PLAYING",
    POSTGAME: "POSTGAME",
};

const TEST_TYPE = {
    VALID: "VALID",
    AVAILABLE: "AVAILABLE",
    EXISTS: "EXISTS",
};

const FIELD_TYPE = {
    USERNAME: "USERNAME",
    EMAIL: "EMAIL",
    PASSWORD: "PASSWORD",
};

const RESULT_TYPE = {
    TOP: "TOP",
    RECENT: "RECENT",
    PLAYER_TOP: "PLAYER_TOP",
    PLAYER_RECENT: "PLAYER_RECENT",
};

export { ACCOUNT_TYPE, STATE, TEST_TYPE, FIELD_TYPE, RESULT_TYPE };
