const keyboard = [
    [
        { display: "ESC", class: "key__esc", code: "Escape" },
        { display: "1", secondary: "!", code: "Digit1" },
        { display: "2", secondary: "@", code: "Digit2" },
        { display: "3", secondary: "#", code: "Digit3" },
        { display: "4", secondary: "$", code: "Digit4" },
        { display: "5", secondary: "%", code: "Digit5" },
        { display: "6", secondary: "^", code: "Digit6" },
        { display: "7", secondary: "&", code: "Digit7" },
        { display: "8", secondary: "*", code: "Digit8" },
        { display: "9", secondary: "(", code: "Digit9" },
        { display: "0", secondary: ")", code: "Digit0" },
        { display: "-", secondary: "_", code: "Minus" },
        { display: "=", secondary: "+", code: "Equal" },
        { display: "BACKSPACE", class: "key__delete", code: "Backspace" },
    ],
    [
        { display: "TAB", class: "key__oneandhalf", code: "Tab" },
        { display: "Q", code: "KeyQ" },
        { display: "W", code: "KeyW" },
        { display: "E", code: "KeyE" },
        { display: "R", code: "KeyR" },
        { display: "T", code: "KeyT" },
        { display: "Y", code: "KeyY" },
        { display: "U", code: "KeyU" },
        { display: "I", code: "KeyI" },
        { display: "O", code: "KeyO" },
        { display: "P", code: "KeyP" },
        { display: "[", secondary: "{", code: "BracketLeft" },
        { display: "]", secondary: "}", code: "BracketRight" },
        { display: "\\", secondary: "|", class: "key__oneandhalf", code: "Backslash" },
    ],
    [
        { display: "CAPS", class: "key__caps", code: "CapsLock" },
        { display: "A", code: "KeyA" },
        { display: "S", code: "KeyS" },
        { display: "D", code: "KeyD" },
        { display: "F", code: "KeyF" },
        { display: "G", code: "KeyG" },
        { display: "H", code: "KeyH" },
        { display: "J", code: "KeyJ" },
        { display: "K", code: "KeyK" },
        { display: "L", code: "KeyL" },
        { display: ";", secondary: ":", code: "Semicolon" },
        { display: "'", secondary: '"', code: "Quote" },
        { display: "ENTER", class: "key__enter", code: "Enter" },
    ],
    [
        { display: "SHIFT", class: "key__shift-left", code: "ShiftLeft" },
        { display: "Z", code: "KeyZ" },
        { display: "X", code: "KeyX" },
        { display: "C", code: "KeyC" },
        { display: "V", code: "KeyV" },
        { display: "B", code: "KeyB" },
        { display: "N", code: "KeyN" },
        { display: "M", code: "KeyM" },
        { display: ",", secondary: "<", code: "Comma" },
        { display: ".", secondary: ">", code: "Period" },
        { display: "/", secondary: "?", code: "Slash" },
        { display: "SHIFT", class: "key__shift-right", code: "ShiftRight" },
    ],
    [
        { display: "CTRL", class: "key__oneandhalf", code: "ControlLeft" },
        { display: "WIN" },
        { display: "ALT", class: "key__alt", code: "AltLeft" },
        { display: "", class: "key__spacebar", code: "Space" },
        { display: "ALT", class: "key__alt", code: "AltRight" },
        { display: "WIN" },
        { display: "" },
        { display: "CTRL", class: "key__oneandhalf", code: "ControlRight" },
    ],
];

export default keyboard;
